sudo: required
services:
  - docker
language: generic
before-install:
  - docker build -t amer211/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true amer211/docker-react npm run test -- --coverage
