name: CI for Docker React

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build Docker image
      - name: Build Docker image
        run: docker build -t docker-react -f Dockerfile.dev .

      # Run tests
      - name: Run tests
        run: docker run -e CI=true docker-react npm test -- --coverage
